---
title: "Gapminder Data Set"
author: "Nipunjeet Gujral"
date: "Jan 01 2019"
  output:
    html_document:
    toc: true
    toc_depth: 3
    toc_float: 
      smooth_scroll: true
    theme: flatly
    highlight: haddock
    code_folding: hide
---


# 0. Senario

# 1. Libraries
```{r load libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(reshape2)
library(googleVis)
```

# 2. Create Data
```{r}
# set reandom seed for reproducability
set.seed(15)

# initialize dataframe with unique oder transcation ids
df <- data.frame(orderID=c(1:1000)) 

# create shopping history of multiple clients
df <- df %>% 
  tibble::add_column(clientID = sample(c(1:1300), 1000, replace = TRUE),
                     prod1 = sample(c('NULL','a'), 1000, replace = TRUE, prob = c(0.15, 0.5)),
                     prod2 = sample(c('NULL','b'), 1000, replace = TRUE, prob = c(0.15, 0.3)),
                     prod3 = sample(c('NULL','c'), 1000, replace = TRUE, prob = c(0.15, 0.2))) %>% 
  dplyr::mutate(cart = paste(prod1, prod2, prod3, sep = ";")) %>% 
  dplyr::mutate(cart = gsub('NULL;|;NULL', '', cart)) %>% 
  dplyr::filter(cart != 'NULL') %>% 
  dplyr::select(orderID, clientID, cart) %>% 
  dplyr::arrange(clientID, orderID, cart)

df %>% head(10)
```

# 3. Calculate number of unique interactions a single client has made
```{r}
# calculate number of order a single client has made
orders <- df %>% 
  dplyr::group_by(clientID) %>% 
  dplyr::mutate(order_num = paste('order', c(1:n()), sep = '')) %>% 
  dplyr::ungroup() %>% 
  dplyr::arrange(desc(order_num))
  
orders %>% head(10)
```

# 4. Make each oder a sperate column
```{r}
orders <- dcast(orders, clientID ~ order_num, value.var='cart', fun.aggregate = NULL) %>% dplyr::filter(ord2 != "NA" & ord3 != "NA" & ord4 != "NA")

orders %>% head(10)
```


# 5. Plot Sankey diagram
```{r}
orders.plot <- data.frame()
 
for (i in 2:ncol(orders)) {
 
 ord.cache <- orders %>%
   group_by(orders[ , i-1], orders[ , i]) %>%
   summarise(n=n()) %>%
   ungroup()
 
 colnames(ord.cache)[1:2] <- c('from', 'to')
 
 # adding tags to carts
 ord.cache$from <- paste(ord.cache$from, '(', i-1, ')', sep='')
 ord.cache$to <- paste(ord.cache$to, '(', i, ')', sep='')
 
 orders.plot <- rbind(orders.plot, ord.cache)
 
}
```


```{r}
plot(gvisSankey(orders.plot, from='from', to='to', weight='n', options=list(height=900, width=1800, sankey="{link:{color:{fill:'lightblue'}}}")))
```

